# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('te_state', models.CharField(choices=[('已租', '已租'), ('可帶', '可帶'), ('查詢', '查詢'), ('無效', '無效'), ('其他', '其他')], default='新打', max_length=20, verbose_name='狀態')),
                ('te_date', models.DateField(auto_now=True, verbose_name='更新時間')),
                ('te_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='網址')),
                ('te_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='電話')),
                ('te_note', models.TextField(blank=True, default=' ', null=True, verbose_name='房客紀錄')),
                ('te_tracetime', models.DateField(blank=True, null=True, verbose_name='追蹤時間')),
            ],
        ),
    ]
