# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='te_money',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='預算'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='te_zone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='想要區域'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='te_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='te_state',
            field=models.CharField(choices=[('新客', '新客'), ('已租', '已租'), ('可帶', '可帶'), ('查詢', '查詢'), ('無效', '無效'), ('其他', '其他')], default='新打', max_length=20, verbose_name='狀態'),
        ),
    ]
