# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtenant', '0003_auto_20180114_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='te_note',
            field=models.TextField(blank=True, default='何時入住: \n預算多少: \n其他需求:', null=True, verbose_name='房客紀錄'),
        ),
    ]
