# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtenant', '0004_auto_20180116_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='te_member',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='負責同仁'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='te_type',
            field=models.CharField(choices=[('套房', '套房'), ('住宅', '住宅'), ('店面', '店面')], default=' ', max_length=20, verbose_name='案件類型'),
        ),
    ]
