# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtenant', '0005_auto_20180226_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='te_date',
            new_name='te_up_date',
        ),
        migrations.AddField(
            model_name='tenant',
            name='te_in_date',
            field=models.DateField(auto_now=True, verbose_name='何時入住'),
        ),
    ]
