# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtenant', '0006_auto_20180226_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='te_in_date',
            field=models.DateField(verbose_name='何時入住'),
        ),
    ]
