# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtenant', '0007_auto_20180226_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='te_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='何時入住'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='te_type',
            field=models.CharField(choices=[('套房', '套房'), ('住宅', '住宅'), ('店面', '店面'), ('其他', '其他')], default='套房', max_length=20, verbose_name='案件類型'),
        ),
    ]
