# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtenant', '0008_auto_20180228_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='te_note',
            field=models.TextField(blank=True, default=' | 何時入住: \n | 預算多少: \n | 其他需求:', null=True, verbose_name='房客紀錄'),
        ),
    ]
