# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_date', models.DateTimeField(auto_now_add=True, verbose_name='搜集時間')),
                ('state', models.CharField(choices=[('未打', '未打'), ('沒接', '沒接'), ('追蹤', '追蹤'), ('失敗', '失敗'), ('成功', '成功')], default='未打', max_length=20, verbose_name='狀態')),
                ('dev_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('dev_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='稱呼')),
                ('dev_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='電話')),
                ('dev_phone_img', models.ImageField(blank=True, max_length=20, null=True, upload_to='dev-phone', verbose_name='電話圖')),
                ('dev_screenshot', models.ImageField(blank=True, null=True, upload_to='dev-phone', verbose_name='網頁截圖')),
                ('dev_note', models.TextField(default=' ', verbose_name='開發紀錄')),
                ('dev_tracetime', models.DateTimeField(auto_now=True, verbose_name='追蹤時間')),
            ],
        ),
    ]
