# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinfo',
            name='dev_date',
            field=models.DateField(auto_now_add=True, verbose_name='搜集時間'),
        ),
        migrations.AlterField(
            model_name='devinfo',
            name='dev_tracetime',
            field=models.DateField(verbose_name='追蹤時間'),
        ),
    ]
