# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0004_auto_20180105_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinfo',
            name='dev_phone_img',
            field=models.FileField(blank=True, null=True, upload_to='dev-phone', verbose_name='電話圖'),
        ),
    ]
