# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0005_auto_20180106_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinfo',
            name='dev_rent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='租金'),
        ),
        migrations.AlterField(
            model_name='devinfo',
            name='dev_note',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='開發紀錄'),
        ),
        migrations.AlterField(
            model_name='devinfo',
            name='dev_phone_img',
            field=models.FileField(null=True, upload_to='dev-phone', verbose_name='電話圖'),
        ),
    ]
