# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0007_auto_20180108_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devinfo',
            options={'verbose_name_plural': '開發資訊'},
        ),
        migrations.AlterField(
            model_name='devinfo',
            name='dev_date',
            field=models.DateField(auto_now_add=True, verbose_name='搜集時間'),
        ),
    ]
