# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0008_auto_20180108_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinfo',
            name='dev_zone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域'),
        ),
    ]
