# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0011_auto_20180111_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinfo',
            name='dev_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='devinfo',
            name='dev_phone_img',
            field=models.ImageField(blank=True, null=True, upload_to='dev-phone', verbose_name='電話圖'),
        ),
    ]
