# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0012_auto_20180111_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinfo',
            name='dev_phone_img',
            field=models.ImageField(null=True, upload_to='dev-phone', verbose_name='電話圖'),
        ),
    ]
