# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0013_auto_20180111_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinfo',
            name='dev_date',
            field=models.DateField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
