# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0014_auto_20180112_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devinfo',
            name='dev_screenshot',
        ),
        migrations.AddField(
            model_name='devinfo',
            name='dev_screenshot_img',
            field=models.ImageField(blank=True, null=True, upload_to='dev-web', verbose_name='網頁截圖'),
        ),
    ]
