# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0015_auto_20180114_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinfo',
            name='dev_phone_img',
            field=models.ImageField(blank=True, null=True, upload_to='dev-phone', verbose_name='電話圖'),
        ),
    ]
