# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0016_auto_20180117_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinfo',
            name='dev_menber',
            field=models.CharField(choices=[('依蓓', '依蓓'), ('寶妮', '寶妮'), ('定騰', '定騰')], default='未打', max_length=20, verbose_name='開發人員'),
        ),
    ]
