# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0017_devinfo_dev_menber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinfo',
            name='dev_menber',
            field=models.CharField(choices=[('未知', '未知'), ('依蓓', '依蓓'), ('寶妮', '寶妮'), ('定騰', '定騰')], default='未知', max_length=20, verbose_name='開發人員'),
        ),
    ]
