# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0018_auto_20180118_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinfo',
            name='dev_pattern',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='格局'),
        ),
    ]
