# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0019_devinfo_dev_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinfo',
            name='dev_source',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='來源'),
        ),
    ]
