# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhouse', '0021_auto_20180123_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinfo',
            name='dev_menber',
            field=models.CharField(default='未知', max_length=20, verbose_name='開發人員'),
        ),
    ]
