# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(blank=True, max_length=60, null=True, verbose_name='案件地址')),
            ],
        ),
        migrations.AddField(
            model_name='homemediainfo',
            name='home_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='home.HomeInfo'),
        ),
    ]
