# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180228_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='home_drink',
            field=models.CharField(default='公共 | 無', max_length=20, verbose_name='飲水'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_elecfee',
            field=models.CharField(choices=[('台電', '台電'), ('5元', '5元'), ('4.5元', '4.5元'), ('4元', '4元'), ('其他補充', '其他補充')], default='台電', max_length=20, verbose_name='電費計算'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_garbage',
            field=models.CharField(choices=[('社區集中', '社區集中'), ('子母車', '子母車'), ('自理', '自理'), ('其他補充', '其他補充')], default='公共', max_length=20, verbose_name='垃圾處理'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_how_inter_door',
            field=models.CharField(choices=[('公司Key', '公司Key'), ('屋主開門', '屋主開門'), ('管理室', '管理室'), ('密碼', '密碼'), ('其他補充', '其他補充')], default='公司Key', max_length=50, verbose_name='如何進入房門'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_how_manage',
            field=models.CharField(choices=[('物管公司', '物管公司'), ('管理員', '管理員'), ('無', '無'), ('其他補充', '其他補充')], default='無', max_length=20, verbose_name='管理方式'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_limit',
            field=models.CharField(default='禁男 | 禁女 | 年紀限制：', max_length=50, verbose_name='其他限制'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_master',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='房東姓名'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_master_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='房東電話'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_no_include',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('水', '水'), ('電', '電'), ('網路', '網路'), ('第四台', '第四台'), ('垃圾費', '垃圾費'), ('管理費', '管理費'), ('其他', '其他')], default='測試', max_length=100, verbose_name='租金不包含'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_note',
            field=models.TextField(default=' ', verbose_name='其他補充'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_pet',
            field=models.CharField(choices=[('全部禁寵', '全部禁寵'), ('可寵', '可寵'), ('可貓', '可貓'), ('可狗', '可狗'), ('其他補充', '其他補充')], default='全部禁寵', max_length=20, verbose_name='寵物限制'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_wash',
            field=models.CharField(default='獨立 | 公用 | 無', max_length=20, verbose_name='洗衣'),
        ),
    ]
