# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180228_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinfo',
            name='home_drink',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='home_elecfee',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='home_limit',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='home_no_include',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='home_pet',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='home_wash',
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_equipment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('桌子', '桌子'), ('椅子', '椅子'), ('衣櫃', '衣櫃'), ('床', '床'), ('沙發', '沙發'), ('熱水器', '熱水器'), ('電視', '電視'), ('冰箱', '冰箱'), ('冷氣', '冷氣'), ('洗衣機', '洗衣機')], default=' ', max_length=100, verbose_name='設備包含'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_fee_note',
            field=models.TextField(default='管理費： \n電費： \n水費： \n其他： ', verbose_name='雜費補充'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_include',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('水', '水'), ('網路', '網路'), ('第四台', '第四台'), ('垃圾費', '垃圾費'), ('管理費', '管理費'), ('其他', '其他')], default='測試', max_length=100, verbose_name='包含雜費'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_park',
            field=models.CharField(default='平面 | 機上/下，車號：', max_length=10, verbose_name='車位'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_people_limit',
            field=multiselectfield.db.fields.MultiSelectField(default='禁男 | 禁女 | 年紀限制：', max_length=100, verbose_name='身份限制'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_pet_limit',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('全部禁寵', '全部禁寵'), ('可寵', '可寵'), ('可貓', '可貓'), ('可狗', '可狗'), ('其他補充', '其他補充')], default=' ', max_length=100, verbose_name='寵物限制'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_rent',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='租金'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_square',
            field=models.CharField(default='10', max_length=10, verbose_name='坪數'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='home_type',
            field=models.CharField(choices=[('大樓', '大樓'), ('公寓', '公寓'), ('透天', '透天'), ('其他', '其他')], default='無', max_length=20, verbose_name='型態'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_note',
            field=models.TextField(default='有無密碼： \n管理方式： \n垃圾處理： \n其他限制： \n', verbose_name='補充資訊'),
        ),
    ]
