# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180301_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='home_address',
            field=models.CharField(default='', max_length=100, verbose_name='案件地址'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_equipment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('桌子', '桌子'), ('椅子', '椅子'), ('衣櫃', '衣櫃'), ('床組', '床組'), ('沙發', '沙發'), ('電視', '電視'), ('冰箱', '冰箱'), ('冷氣', '冷氣'), ('熱水器', '熱水器'), ('洗衣機', '洗衣機')], max_length=100, null=True, verbose_name='設備包含'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_park',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='車位'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_partten',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='格局'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_people_limit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('學生', '學生'), ('家庭', '家庭'), ('上班族', '上班族'), ('禁男', '禁男'), ('禁女', '禁女'), ('禁小孩', '禁小孩'), ('禁拜拜', '禁拜拜'), ('禁煮飯', '禁煮飯'), ('其他補充', '其他補充')], max_length=100, null=True, verbose_name='身份限制'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_pet_limit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('可寵', '可寵'), ('可貓', '可貓'), ('可狗', '可狗'), ('全部禁寵', '全部禁寵'), ('其他補充', '其他補充')], max_length=100, null=True, verbose_name='寵物限制'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_square',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='坪數'),
        ),
    ]
