# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180301_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='home_fee_note',
            field=models.TextField(default=' | 管理費： \n | 電費： \n | 水費： \n | 其他： ', verbose_name='雜費補充'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_garbage',
            field=models.CharField(blank=True, choices=[('社區集中', '社區集中'), ('子母車', '子母車'), ('自理', '自理'), ('請看補充資訊', '請看補充資訊')], max_length=20, null=True, verbose_name='垃圾處理'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_how_inter_door',
            field=models.CharField(blank=True, choices=[('公司Key', '公司Key'), ('屋主開門', '屋主開門'), ('管理室', '管理室'), ('密碼', '密碼'), ('請看補充資訊', '請看補充資訊')], max_length=50, null=True, verbose_name='如何進入房門'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_how_manage',
            field=models.CharField(blank=True, choices=[('物管公司', '物管公司'), ('管理員', '管理員'), ('無', '無'), ('請看補充資訊', '請看補充資訊')], max_length=20, null=True, verbose_name='管理方式'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_note',
            field=models.TextField(default=' | 如何進入大門： \n | 管理方式： \n | 垃圾處理： \n | 其他限制問題： \n', verbose_name='補充資訊'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_people_limit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('學生', '學生'), ('家庭', '家庭'), ('上班族', '上班族'), ('禁男', '禁男'), ('禁女', '禁女'), ('禁小孩', '禁小孩'), ('禁拜拜', '禁拜拜'), ('禁煮飯', '禁煮飯'), ('請看補充資訊', '請看補充資訊')], max_length=100, null=True, verbose_name='身份限制'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_pet_limit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('可寵', '可寵'), ('可貓', '可貓'), ('可狗', '可狗'), ('全部禁寵', '全部禁寵'), ('請看補充資訊', '請看補充資訊')], max_length=100, null=True, verbose_name='寵物限制'),
        ),
        migrations.AlterField(
            model_name='homemediainfo',
            name='home_title',
            field=models.CharField(default='', max_length=60, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='homephoto',
            name='h_image',
            field=models.FileField(default='', upload_to='home_photo/%Y-%m-%d', verbose_name='照片'),
        ),
    ]
