# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180301_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='home_fee_note',
            field=models.TextField(default='管理費： \n電費： \n水費： \n其他： ', verbose_name='雜費補充'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_note',
            field=models.TextField(default='如何進入大門： \n管理方式： \n垃圾處理： \n其他限制問題： \n', verbose_name='補充資訊'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_people_limit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('禁報稅', '禁報稅'), ('禁入戶籍', '禁入戶籍'), ('學生', '學生'), ('家庭', '家庭'), ('上班族', '上班族'), ('禁男', '禁男'), ('禁女', '禁女'), ('禁小孩', '禁小孩'), ('禁拜拜', '禁拜拜'), ('禁煮飯', '禁煮飯'), ('請看補充資訊', '請看補充資訊')], max_length=100, null=True, verbose_name='身份限制'),
        ),
    ]
