# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180302_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='home_garbage',
            field=models.CharField(blank=True, choices=[('自理', '自理'), ('子母車', '子母車'), ('社區集中', '社區集中'), ('請看補充資訊', '請看補充資訊')], max_length=20, null=True, verbose_name='垃圾處理'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='home_how_manage',
            field=models.CharField(blank=True, choices=[('自理', '自理'), ('管理員', '管理員'), ('物管公司', '物管公司'), ('請看補充資訊', '請看補充資訊')], max_length=20, null=True, verbose_name='管理方式'),
        ),
    ]
