# Generated by Django 2.0 on 2017-12-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_address', models.CharField(default='台中市', max_length=60, verbose_name='案件地址')),
                ('suite_how_inter_housedoor', models.CharField(default='公司Key|密碼|屋主開門', max_length=50, verbose_name='如何進入案件')),
                ('suite_how_inter_roomdoor', models.CharField(default='公司Key|藏在現場|沒鎖|屋主開門', max_length=50, verbose_name='如何進入房門')),
                ('suite_include', models.CharField(choices=[('1', '水'), ('2', '電'), ('3', '網路'), ('4', '第四台'), ('5', '垃圾費'), ('6', '管理費'), ('7', '其他')], max_length=150, verbose_name='租金包含')),
                ('suite_no_include', models.CharField(default='水:100/人|100/第2人,', max_length=100, verbose_name='租金不包含')),
                ('suite_garbage', models.CharField(default='公共|無', max_length=20, verbose_name='垃圾處理')),
                ('suite_wash', models.CharField(default='獨立|公用|無', max_length=20, verbose_name='洗衣')),
                ('suite_drink', models.CharField(default='自理|無', max_length=20, verbose_name='飲水')),
                ('suite_limit', models.CharField(default='全部禁寵|部份禁寵:可貓|禁男', max_length=50, verbose_name='限制條件')),
                ('suite_note', models.TextField(default='', verbose_name='其他補充')),
            ],
            options={
                'verbose_name': '房屋資訊',
            },
        ),
    ]
