# Generated by Django 2.0 on 2017-12-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0002_auto_20171231_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='suite.Suites'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_address',
            field=models.CharField(max_length=60, verbose_name='案件地址'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_include',
            field=models.CharField(max_length=150, verbose_name='租金包含'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_note',
            field=models.TextField(default=' ', verbose_name='其他補充'),
        ),
    ]
