# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0004_auto_20180101_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house_photo',
            options={},
        ),
        migrations.AlterField(
            model_name='house_photo',
            name='P_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='suite.Suites'),
        ),
        migrations.AlterField(
            model_name='house_photo',
            name='p_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='house_photo',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='suite_photos'),
        ),
        migrations.AlterField(
            model_name='house_photo',
            name='p_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='suite.Suites'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_address',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='案件地址'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_include',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='租金包含'),
        ),
    ]
