# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0005_auto_20180104_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House_photo',
            new_name='Suite_photo',
        ),
    ]
