# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0006_auto_20180104_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suite_photo',
            options={'verbose_name_plural': '照片'},
        ),
        migrations.AlterField(
            model_name='suite_photo',
            name='p_image',
            field=models.FileField(blank=True, null=True, upload_to='suite_photos', verbose_name='上傳照片'),
        ),
        migrations.AlterField(
            model_name='suite_photo',
            name='p_subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='標題'),
        ),
    ]
