# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0007_auto_20180104_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite_photo',
            name='p_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='照片'),
        ),
    ]
