# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0010_auto_20180104_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite_photo',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='suite_photos/%Y-%m-%d/', verbose_name='照片'),
        ),
    ]
