# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0011_auto_20180104_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite_photo',
            name='p_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='suite_photo',
            name='p_image',
            field=models.FileField(blank=True, null=True, upload_to='suite_photos/%Y-%m-%d/', verbose_name='照片'),
        ),
    ]
