# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
#import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0012_auto_20180104_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite_photo',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='suite_photos/%Y-%m-%d/', verbose_name='照片'),
        ),
    ]
