# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0013_auto_20180104_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='標題')),
                ('p_image', models.FileField(blank=True, null=True, upload_to='suite_photo/%Y-%m-%d/', verbose_name='照片')),
                ('p_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('P_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='suite.Suites')),
            ],
            options={
                'verbose_name_plural': '照片',
            },
        ),
        migrations.RemoveField(
            model_name='suite_photo',
            name='P_address',
        ),
        migrations.RemoveField(
            model_name='suite_photo',
            name='p_image',
        ),
        migrations.DeleteModel(
            name='Suite_photo',
        ),
    ]
