# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0014_auto_20180104_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitephoto',
            name='p_image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
