# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0015_auto_20180104_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitephoto',
            name='p_image',
            field=models.FileField(blank=True, null=True, upload_to='suite_photo/%Y-%m-%d', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_drink',
            field=models.CharField(default='公共 | 無', max_length=20, verbose_name='飲水'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_elecfee',
            field=models.CharField(default='5元 | 台電,', max_length=10, verbose_name='電費計算'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_garbage',
            field=models.CharField(default='公共 | 無', max_length=20, verbose_name='垃圾處理'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_how_inter_housedoor',
            field=models.CharField(default='公司Key | 密碼 | 管理室 | 屋主開門', max_length=50, verbose_name='如何進入案件'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_how_inter_roomdoor',
            field=models.CharField(default='公司Key | 藏在現場 | 沒鎖 | 屋主開門', max_length=50, verbose_name='如何進入房門'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_limit',
            field=models.CharField(default='全部禁寵 | 部份禁寵:可貓 | 禁男', max_length=50, verbose_name='限制條件'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_no_include',
            field=models.CharField(default='水:100/人 | 100/第2人 ,', max_length=100, verbose_name='租金不包含'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='suite_wash',
            field=models.CharField(default='獨立 | 公用 | 無', max_length=20, verbose_name='洗衣'),
        ),
    ]
