# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0017_auto_20180109_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suites',
            options={'verbose_name_plural': '套房案件'},
        ),
    ]
