# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0019_auto_20180301_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_fullrent', models.BooleanField(default=True, verbose_name='可租狀態')),
                ('room_number', models.CharField(default='X', max_length=10, verbose_name='房號')),
                ('room_rent', models.PositiveIntegerField(blank=True, null=True, verbose_name='價位')),
                ('room_description', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='備註')),
            ],
            options={
                'verbose_name_plural': '空房資訊',
            },
        ),
        migrations.CreateModel(
            name='SuitePhotoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(default='', max_length=60, verbose_name='標題')),
            ],
            options={
                'verbose_name_plural': '照片資訊',
            },
        ),
        migrations.RenameModel(
            old_name='Suites',
            new_name='Suite',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='room_address',
        ),
        migrations.AlterModelOptions(
            name='suitephoto',
            options={'verbose_name_plural': '套房照片'},
        ),
        migrations.RemoveField(
            model_name='suitephoto',
            name='P_address',
        ),
        migrations.RemoveField(
            model_name='suitephoto',
            name='p_date',
        ),
        migrations.RemoveField(
            model_name='suitephoto',
            name='p_image',
        ),
        migrations.RemoveField(
            model_name='suitephoto',
            name='p_subject',
        ),
        migrations.AddField(
            model_name='suitephoto',
            name='s_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suitephoto',
            name='s_image',
            field=models.FileField(default='', upload_to='suite_photo/%Y-%m-%d', verbose_name='照片'),
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.AddField(
            model_name='suitephotoinfo',
            name='s_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_photo', to='suite.Suite'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='suite.Suite'),
        ),
        migrations.AddField(
            model_name='suitephoto',
            name='s_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='suite.SuitePhotoInfo', verbose_name='標題'),
        ),
    ]
