# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0020_auto_20180301_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_fullrent',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_rent',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_description',
            field=models.TextField(blank=True, default=' ', max_length=50, null=True, verbose_name='備註'),
        ),
    ]
