# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0021_auto_20180302_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_address',
        ),
        migrations.AddField(
            model_name='suite',
            name='suite_room',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='目前空房'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
