# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_address', models.CharField(default='', max_length=100, verbose_name='案件地址')),
                ('store_master', models.CharField(blank=True, max_length=20, null=True, verbose_name='房東姓名')),
                ('store_master_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='房東電話')),
                ('store_how_inter_door', models.CharField(blank=True, choices=[('公司Key', '公司Key'), ('屋主開門', '屋主開門'), ('管理室', '管理室'), ('密碼', '密碼'), ('請看補充資訊', '請看補充資訊')], max_length=50, null=True, verbose_name='如何進入房門')),
                ('store_type', models.CharField(blank=True, choices=[('透店', '透店'), ('樓店', '樓店'), ('小商場', '小商場'), ('大商場', '大商場'), ('辦公室', '辦公室'), ('廠房', '廠房'), ('土地', '土地'), ('請看補充資訊', '請看補充資訊')], max_length=20, null=True, verbose_name='型態')),
                ('store_floor', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='使用樓層')),
                ('store_square', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='坪數')),
                ('store_how_manage', models.CharField(blank=True, choices=[('無', '無'), ('物管公司', '物管公司'), ('管理員', '管理員'), ('請看補充資訊', '請看補充資訊')], max_length=20, null=True, verbose_name='管理方式')),
                ('store_garbage', models.CharField(blank=True, choices=[('自理', '自理'), ('社區集中', '社區集中'), ('子母車', '子母車'), ('請看補充資訊', '請看補充資訊')], max_length=20, null=True, verbose_name='垃圾處理')),
                ('store_partten', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='格局')),
                ('store_park', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='車位')),
                ('store_rent', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='租金')),
                ('store_include', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('水', '水'), ('網路', '網路'), ('第四台', '第四台'), ('垃圾費', '垃圾費'), ('管理費', '管理費'), ('其他', '其他')], max_length=100, null=True, verbose_name='包含雜費')),
                ('store_fee_note', models.TextField(default='租金含稅： \n管理費： \n電費： \n水費： \n其他： ', verbose_name='雜費補充')),
                ('store_equipment', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('桌子', '桌子'), ('椅子', '椅子'), ('衣櫃', '衣櫃'), ('床組', '床組'), ('沙發', '沙發'), ('電視', '電視'), ('冰箱', '冰箱'), ('冷氣', '冷氣'), ('熱水器', '熱水器'), ('洗衣機', '洗衣機')], max_length=100, null=True, verbose_name='設備包含')),
                ('store_people_limit', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('禁報稅', '禁報稅'), ('禁八大', '禁八大'), ('全禁餐飲類', '全禁餐飲類'), ('可飲料店', '可飲料店'), ('可輕食店', '可輕食店'), ('請看補充資訊', '請看補充資訊')], max_length=100, null=True, verbose_name='租客限制')),
                ('store_note', models.TextField(default='如何進入大門： \n管理方式： \n垃圾處理： \n其他限制問題： \n', verbose_name='補充資訊')),
            ],
            options={
                'verbose_name_plural': '店面案件',
            },
        ),
        migrations.CreateModel(
            name='StoreMediaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_title', models.CharField(default='', max_length=60, verbose_name='標題')),
                ('store_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_photo', to='store.StoreInfo')),
            ],
            options={
                'verbose_name_plural': '照片資訊',
            },
        ),
        migrations.CreateModel(
            name='StorePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_image', models.FileField(default='', upload_to='home_photo/%Y-%m-%d', verbose_name='照片')),
                ('s_date', models.DateTimeField(auto_now_add=True)),
                ('s_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='store.StoreMediaInfo', verbose_name='標題')),
            ],
            options={
                'verbose_name_plural': '店面照片',
            },
        ),
    ]
