# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='store_people_limit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('禁報稅', '禁報稅'), ('禁八大', '禁八大'), ('全禁餐飲', '全禁餐飲'), ('可飲料店', '可飲料店'), ('可輕食店', '可輕食店'), ('請看補充資訊', '請看補充資訊')], max_length=100, null=True, verbose_name='租客限制'),
        ),
        migrations.AlterField(
            model_name='storephoto',
            name='s_image',
            field=models.FileField(default='', upload_to='store_photo/%Y-%m-%d', verbose_name='照片'),
        ),
    ]
