# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gostreet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images_street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='street_images', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='images_street',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gostreet.Post'),
        ),
    ]
