# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import gostreet.models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AlterField(
            model_name='images_street',
            name='image',
            field=models.ImageField(upload_to=gostreet.models.get_image_filename, verbose_name='掃街照片'),
        ),
    ]
