# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gostreet.models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0003_auto_20180117_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MediaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('media_file', models.FileField(upload_to='street_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='images_street',
            name='img_street',
        ),
        migrations.DeleteModel(
            name='Images_street',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='media',
            name='media_files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gostreet.MediaInfo'),
        ),
    ]
