# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gostreet.models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0004_auto_20180117_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediainfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mediainfo',
            name='media_file',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.FileField(default=2, upload_to=gostreet.models.get_image_filename),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='media_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_title', to='gostreet.MediaInfo', verbose_name='案件地址'),
        ),
    ]
