# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0007_auto_20180117_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_address', to='gostreet.MediaInfo', verbose_name='現場照片'),
        ),
    ]
