# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0010_auto_20180118_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='street_images', verbose_name='現場照片'),
        ),
    ]
