# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0012_auto_20180118_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediainfo',
            options={'verbose_name_plural': '掃街資訊'},
        ),
        migrations.AddField(
            model_name='mediainfo',
            name='now_state',
            field=models.CharField(choices=[('新接', '新接'), ('屋主', '屋主'), ('查詢', '查詢'), ('拜訪', '拜訪'), ('失敗', '失敗'), ('成功', '成功')], default='新接', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_note',
            field=models.CharField(blank=True, default='.', max_length=50, null=True, verbose_name='照片說明'),
        ),
    ]
