# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0013_auto_20180121_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediainfo',
            name='now_transcript_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='戶籍地址'),
        ),
        migrations.AddField(
            model_name='mediainfo',
            name='now_transcript_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所有權人'),
        ),
        migrations.AddField(
            model_name='mediainfo',
            name='now_transcript_note',
            field=models.TextField(blank=True, default='.', null=True, verbose_name='查詢記錄'),
        ),
    ]
