# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0014_auto_20180122_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediainfo',
            name='dev_date',
            field=models.DateField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='mediainfo',
            name='dev_tracetime',
            field=models.DateField(blank=True, null=True, verbose_name='追蹤時間'),
        ),
    ]
