# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0015_auto_20180122_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediainfo',
            old_name='dev_date',
            new_name='now_date',
        ),
        migrations.RenameField(
            model_name='mediainfo',
            old_name='dev_tracetime',
            new_name='now_tracetime',
        ),
    ]
