# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0016_auto_20180122_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediainfo',
            name='now_type',
            field=models.CharField(choices=[('店面', '店面'), ('套房', '套房'), ('住宅', '住宅'), ('其他', '其他')], default='新接', max_length=20, verbose_name='類型'),
        ),
    ]
