# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0017_mediainfo_now_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_date', models.DateField(auto_now_add=True, verbose_name='建立時間')),
                ('fake_state', models.CharField(choices=[('未打', '未打'), ('收養', '收養'), ('完成', '完成')], default='未打', max_length=20, verbose_name='狀態')),
                ('fake_tenant', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='認養人')),
                ('fake_url', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='網址')),
                ('fake_source', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='來源')),
                ('fake_zone', models.CharField(blank=True, max_length=10, null=True, verbose_name='區域')),
                ('fake_pattern', models.CharField(blank=True, max_length=30, null=True, verbose_name='格局')),
                ('fake_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='網路地址')),
                ('fake_real_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='真實地址')),
                ('fake_rent', models.CharField(blank=True, max_length=50, null=True, verbose_name='租金')),
                ('fake_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='稱呼')),
                ('fake_phone_img', models.ImageField(blank=True, null=True, upload_to='dev-phone', verbose_name='電話圖')),
                ('fake_screenshot_img', models.ImageField(blank=True, null=True, upload_to='dev-web', verbose_name='網頁截圖')),
                ('fake_note', models.TextField(blank=True, default=' ', null=True, verbose_name='開發紀錄')),
                ('fake_tracetime', models.DateField(blank=True, null=True, verbose_name='追蹤時間')),
                ('fake_transcript_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='所有權人')),
                ('fake_transcript_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='戶籍地址')),
                ('fake_transcript_note', models.TextField(blank=True, default='.', null=True, verbose_name='查詢記錄')),
            ],
            options={
                'verbose_name_plural': '假房客搜集資訊',
            },
        ),
    ]
