# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0018_fakeinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakeinfo',
            options={'verbose_name_plural': '假房搜集'},
        ),
        migrations.AlterField(
            model_name='fakeinfo',
            name='fake_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='網址'),
        ),
    ]
