# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0020_auto_20180123_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakeinfo',
            name='fake_pattern',
        ),
    ]
