# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostreet', '0021_remove_fakeinfo_fake_pattern'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': '現場照片'},
        ),
        migrations.AddField(
            model_name='mediainfo',
            name='now_manber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='開發人'),
        ),
        migrations.AlterField(
            model_name='mediainfo',
            name='now_note',
            field=models.TextField(default='租金價位: \n是否仲介: \n其他注意:', verbose_name='紀錄備忘'),
        ),
    ]
