# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devstreet', '0004_picture_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='street',
        ),
    ]
