# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devstreet', '0006_auto_20180113_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='JPicture',
        ),
        migrations.RemoveField(
            model_name='goimage',
            name='go_street',
        ),
        migrations.DeleteModel(
            name='Goimage',
        ),
        migrations.DeleteModel(
            name='GoStreet',
        ),
    ]
