# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devstreet', '0007_auto_20180113_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('file', models.ImageField(upload_to='pictures')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JPicture',
        ),
    ]
