# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devstreet', '0008_auto_20180113_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoStreet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='street',
        ),
    ]
