# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devstreet', '0009_auto_20180114_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='照片說明'),
        ),
    ]
